FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

COPY relay-server ./relay-server

EXPOSE 8080

CMD ["node", "relay-server/index.mjs"]
